export interface CurrentUser {
  email: string;
  timeLogin?: Date;
  role: string;
  sessionExpiresAt: Date;
}

export interface Message {
  message: string;
}

export interface Category {
  name: string;
  quantity: number;
  imageSrc?: string;
  user?: string;
  _id?: string;
}

export interface Position {
  name: string;
  cost: number;
  category: string;
  user?: string;
  _id?: string;
  quantity?: number;
}

export interface Order {
  date?: Date;
  order?: number;
  user?: string;
  list: OrderPosition[];
  _id?: string;
}

export interface OrderPosition {
  name: string;
  cost: number;
  quantity: number;
  _id?: string;
}

export interface Filter {
  start?: Date;
  end?: Date;
  order?: number;
}

export interface OverviewPage {
  orders: OverviewPageItem;
  gain: OverviewPageItem;
}

export interface OverviewPageItem {
  percent: number;
  compare: number;
  yesterday: number;
  isHigher: boolean;
}

export interface AnalyticsPage {
  average: number;
  chart: AnalyticsChartItem[];
}

export interface AnalyticsChartItem {
  gain: number;
  order: number;
  label: string;
}

export interface AuthResponse {
  token: string;
  // Puedes incluir otros campos según lo que tu backend devuelva
  // Por ejemplo:
  currentUser: CurrentUser;
  // expiresIn: Date;
  // roles: string[];
}

// Generated by https://quicktype.io

export interface User {
  _id?: string;
  email: string;
  loginAttempts?: number;
  role?: string;
  timeLogin?: string;
  password: string;
}

export enum Role {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  USER = 'USER',
  GUEST = 'GUEST',
}

export interface Coordinates {
  latitude: number;
  longitude: number;
}

export interface Location {
  country: string;
  city: string;
  address: string;
  coordinates?: Coordinates; // Las coordenadas son opcionales
}

export interface ContactInfo {
  phoneNumber?: string; // Opcional
  email?: string; // Opcional
}

export interface Warehouse {
  _id?: string; // Opcional porque no se necesita para la creación
  name: string;
  location: Location;
  capacity: number;
  operationalStatus: 'Active' | 'Inactive' | 'Under Maintenance';
  contactInfo?: ContactInfo; // La información de contacto es opcional
}

export interface Price {
  amount: number;
  currency: string;
}

export interface Tire {
  _id?: string; // Opcional porque no se necesita para la creación
  brand: string;
  model: string;
  size: string;
  type: 'Winter' | 'Summer' | 'All-Season' | 'Off-Road';
  manufactureDate: Date;
  countryOfOrigin: string;
  warehouseId: string; // O puedes usar `mongoose.Schema.Types.ObjectId` si trabajas directamente con referencias de Mongoose
  quantityInStock: number;
  price: Price;
  warehouseName: string;
  warehouseInfo?: Warehouse; // Hacerlo opcional si no siempre está presente
}

export interface WarehouseResponse {
  tireId: string;
  warehouseName: string;
}

export interface FormFieldOption {
  value: string;
  label: string;
}

export interface FormField {
  type: 'input' | 'select' | 'date' | 'group' | 'text'; // Añade más tipos según sea necesario
  label: string;
  name: string;
  validators?: any[]; // Array de validadores
  options?: FormFieldOption[]; // Solo para campos de tipo 'select'
  inputType?: string; // Solo para campos de tipo 'input'
  fields?: FormGroupConfig; // Solo para campos de tipo 'group', para anidación
  class?: string; // Permite la asignación dinámica de clases CSS
  dataPpicker?: boolean
}

export interface FormGroupConfig {
  [key: string]: FormField;
}
