export interface CurrentUser {
  email: string;
  timeLogin?: Date;
  role: string;
  sessionExpiresAt: Date;
}

export interface Message {
  message: string;
}

export interface Category {
  name: string;
  quantity: number;
  imageSrc?: string;
  user?: string;
  _id?: string;
}

export interface Position {
  name: string;
  cost: number;
  category: string;
  user?: string;
  _id?: string;
  quantity?: number;
}

export interface Order {
  date?: Date;
  order?: number;
  user?: string;
  list: OrderPosition[];
  _id?: string;
}

export interface OrderPosition {
  name: string;
  cost: number;
  quantity: number;
  _id?: string;
}

export interface Filter {
  start?: Date;
  end?: Date;
  order?: number;
}

export interface OverviewPage {
  orders: OverviewPageItem;
  gain: OverviewPageItem;
}

export interface OverviewPageItem {
  percent: number;
  compare: number;
  yesterday: number;
  isHigher: boolean;
}

export interface AnalyticsPage {
  average: number;
  chart: AnalyticsChartItem[];
}

export interface AnalyticsChartItem {
  gain: number;
  order: number;
  label: string;
}

export interface AuthResponse {
  token: string;
  // Puedes incluir otros campos según lo que tu backend devuelva
  // Por ejemplo:
  currentUser: CurrentUser;
  // expiresIn: Date;
  // roles: string[];
}

// Generated by https://quicktype.io

export interface User {
  _id?: string;
  email: string;
  loginAttempts?: number;
  __v?: number;
  role?: string;
  timeLogin?: string;
  password: string;
}

export enum Role {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  USER = 'USER',
  GUEST = 'GUEST',
}

export interface Coordinates {
  latitude: number;
  longitude: number;
}

export interface Location {
  country: string;
  city: string;
  address: string;
  coordinates?: Coordinates; // Las coordenadas son opcionales
}

export interface ContactInfo {
  phoneNumber?: string; // Opcional
  email?: string;        // Opcional
}

export interface Warehouse {
  _id?: string; // Opcional porque no se necesita para la creación
  name: string;
  location: Location;
  capacity: number;
  operationalStatus: 'Active' | 'Inactive' | 'Under Maintenance';
  contactInfo?: ContactInfo; // La información de contacto es opcional
}
